export const EcransEnum = {
    ACCUEIL: "ACCUEIL",
    DASHBOARD: "DASHBOARD",
    SUIVI_CLIENT: "SUIVI_CLIENT",
    INTEGRATION_OPERATIONS: "INTEGRATION_OPERATIONS",
    INTEGRATION_ECHEANCES: "INTEGRATION_ECHEANCES",
    ENCOURS_CLIENT: "ENCOURS_CLIENT",
    ENCOURS_FOURNISSEUR: "ENCOURS_FOURNISSEUR",
    LISTE_OPERATIONS: "LISTE_OPERATIONS",
    ETAT_BANQUE: "ETAT_BANQUE",
    LISTE_CLIENT: "LISTE_CLIENT",
    LISTE_FOURNISSEUR: "LISTE_FOURNISSEUR",
    GESTION_UTILISATEURS: "GESTION_UTILISATEURS",
    GESTION_ROLES: "GESTION_ROLES"
}